sudo: required
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix

language: php
php:
- 5.6
- 7.0

env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=integration INTEGRATION_INDEX=1
    - TEST_SUITE=integration INTEGRATION_INDEX=2
    - TEST_SUITE=integration INTEGRATION_INDEX=3
    - TEST_SUITE=static

cache:
  apt: true
  directories: "$HOME/.composer/cache"

matrix:
  exclude:
  - php: 7.0
    env: TEST_SUITE=static

before_install:
  - openssl aes-256-cbc -K $encrypted_e0b1e0c2baff_key -iv $encrypted_e0b1e0c2baff_iv -in tests/auth.json.enc -out ~/.composer/auth.json -d
  - bin/composer.phar install --no-interaction --prefer-dist --dev
  - sudo ./dev/travis/before_install.sh

install: 
  - composer install --no-interaction --prefer-dist

before_script: 
  - sudo ./dev/travis/before_script.sh

script:
  - cd dev/tests/$TEST_SUITE
  - test $TEST_SUITE = "static" && TEST_FILTER='--filter "Magento\\Test\\Php\\LiveCodeTest"' || true
  - phpunit $TEST_FILTER

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
