sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  firefox: "46.0"
  hosts:
      - magento2.travis
language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
    - NODE_JS_VERSION=6
    - MAGENTO_HOST_NAME="magento2.travis"
    # Magento Download Credentials
    - secure: "bcMyf+Z+WQIbiJdGuPcdBoh39hRJrc6HBk58ujqtvYwcTF3vR7F098rNU1TvrHkyijFgDgQsH2MjKDyeeTf4TgvEqIRH8xZqL0mzSafsGURXKwrdtBL3hS14b636guVbWoqjswpUOsUCvw5ziqJHfvHwXPyP+l+uMAVr6JEFYopQ2rfeUk1z4dGnX/t7nAr1AUM8IJyaKgJ3154cJg8aCfFfJHoR7g+X8UXrJJpjORFIoOsxftUV6TsW4aXfEJ2dhlVU03i04KOt4sP/VRolQmnuKm/cH4fWegCPQx6PNmcb+dqmmhGFVt/ZBtuU4l5WFBFj3pdRqw9gpTNjEClmYfv1ZsPxLRgTrADy1b3L/qfjBVUB8Pw6h4zA/ii6ESXCN0PUWaL09ZVmKHDPtX1Tk2cbP3yOnjgEVfr3CPgNozId8ZfSpQaDK41ietziobOt4YhZCoIjlMfRf8wq18Uft8e1cBt9+zAUNN+K4wzRWSMCa8O3QtpbcpnHyBwid2SJmldAFYbp9NGKPlwk1xPSwSXwgSy0d9N/Uja1Y/F2/qWqMpiSAu/vOv0GqG+6h0MlObtOsVcxpsy41PZelSZ6dmOYAsH+sIqDa7cF2d0EMYbqlJh3379x0i2+Lt0qLMUum26AmzUteSj3m5tlHw1/NRwVahSmAmlgAfI5E6CjEpM="
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=static
    - TEST_SUITE=js GRUNT_COMMAND=spec
    - TEST_SUITE=js GRUNT_COMMAND=static
    - TEST_SUITE=integration INTEGRATION_INDEX=1
    - TEST_SUITE=integration INTEGRATION_INDEX=2
    - TEST_SUITE=integration INTEGRATION_INDEX=3
    - TEST_SUITE=functional ACCEPTANCE_INDEX=1
    - TEST_SUITE=functional ACCEPTANCE_INDEX=2
matrix:
  exclude:
    - php: 7.0
      env: TEST_SUITE=static
    - php: 7.0
      env: TEST_SUITE=js GRUNT_COMMAND=spec
    - php: 7.0
      env: TEST_SUITE=js GRUNT_COMMAND=static
    - php: 7.0
      env: TEST_SUITE=functional ACCEPTANCE_INDEX=1
    - php: 7.0
      env: TEST_SUITE=functional ACCEPTANCE_INDEX=2
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install: ./dev/travis/before_install.sh
install: composer install --no-interaction --prefer-dist
before_script: ./dev/travis/before_script.sh
script:
  # Set arguments for variants of phpunit based tests; '|| true' prevents failing script when leading test fails
  - test $TEST_SUITE = "static" && TEST_FILTER='--filter "Magento\\Test\\Php\\LiveCodeTest"' || true
  - test $TEST_SUITE = "functional" && TEST_FILTER='dev/tests/functional/testsuites/Magento/Mtf/TestSuite/InjectableTests.php' || true

  # The scripts for grunt/phpunit type tests
  - if [ $TEST_SUITE == "functional" ]; then dev/tests/functional/vendor/phpunit/phpunit/phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER; fi
  - if [ $TEST_SUITE != "functional" ] && [ $TEST_SUITE != "js" ]; then phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER; fi
  - if [ $TEST_SUITE == "js" ]; then grunt $GRUNT_COMMAND; fi
